version: "2"
services:

  chronix:
    container_name: chronix
    environment:
      - JAVA_MEMORY=4g
    hostname: chronix
    image: 'hurence/chronix:0.2.0'
    ports:
      - '8983:8983'
    network_mode: bridge

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    network_mode: bridge

  keycloak:
    container_name: keycloak
    image: 'hurence/keycloak:0.2.0'
    ports:
      - '8080:8080'
    network_mode: bridge
    volumes:
       - ../../../../../historian/frontend/keycloak/themes/logisland.historian/:/opt/jboss/keycloak/themes/logisland.historian
       - ../../../../../historian/frontend/keycloak/themes/base.logisland.historian/:/opt/jboss/keycloak/themes/base.logisland.historian
