sudo: required

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

    
language: java

before_script:
  - export DISPLAY=:99.0          #set up virtual screen for front test
  - sh -e /etc/init.d/xvfb start  #set up virtual screen for front test
  - sleep 3 # give xvfb some time to start

script:
  - cd historian
  - mvn clean install

jdk:
  - oraclejdk8

notifications:
  email:
    - bailet.thomas@gmail.com
    - s.h.gregoire@gmail.com

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e305a73a60a02fefba40
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always




