version: "3.3"
services:

  chronix:
    hostname: chronix
    container_name: chronix
    image: 'hurence/chronix:latest'
   # network_mode: host
    ports:
      - '8983:8983'
    networks:
      - itnet

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - itnet

  keycloak:
    container_name: keycloak
    image: 'hurence/keycloak:latest'
    ports:
      - '8080:8080'
    networks:
      - itnet

#  historian:
#    container_name: historian
#    image: 'hurence/historian:latest'
#    ports:
#      - '8701:8701'
#    networks:
#      - itnet

#
#  logisland:
#    #command: /bin/bash bin/logisland.sh --conf conf/mqtt-to-historian.yml
#    command: tail -f bin/logisland.sh
#    environment:
#      - MQTT_BROKER_URL=tcp://51.15.164.141:1883
#
#    hostname: kapua-logisland
#    container_name: kapua-logisland
#    image: 'hurence/logisland:0.12.0'
#    ports:
#      - '4050:4050'
#      - '8008:8008'
#    volumes:
#      - ./conf/logisland:/conf
#      - ./data/logisland:/data
#    networks:
#      - itnet

networks:
  itnet: