version: "2"
services:

  chronix:
    container_name: chronix
    environment:
      - JAVA_MEMORY=4g
    hostname: chronix
    image: 'hurence/historian-chronix:0.4.3'
    ports:
      - '8983:8983'
    network_mode: bridge

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    network_mode: bridge

  keycloak:
    container_name: keycloak
    image: 'hurence/keycloak:0.2.0'
    ports:
      - '8080:8080'
    network_mode: bridge

  # historian-backend:
  #   container_name: historian-backend
  #   image: 'hurence/historian-backend:0.3.0'
  #   ports:
  #     - '8701:8701'
  #   links:
  #     - chronix
  #     - redis
  #     - keycloak
  #   network_mode: bridge

  # historian-frontend:
  #   container_name: historian-frontend
  #   image: 'hurence/historian-frontend:0.3.0'
  #   ports:
  #     - '4200:80'
  #   links:
  #     - historian-backend
  #     - keycloak
  #   network_mode: bridge

  logisland:
    container_name: logisland
    image: 'hurence/logisland:0.14.1-develop'
    command: tail -f bin/logisland.sh
    hostname: logisland
    ports:
      - '4050:4050'
    links:
      # - zookeeper
      # - kafka
      # - elasticsearch
      - chronix
      - redis
      # - historian-backend
    extra_hosts:
      - "historian:172.17.0.1"
    network_mode: bridge
