version: "3"
networks:
  historian-be:

services:
  chronix:
    container_name: chronix
    environment:
      - JAVA_MEMORY=1g
    hostname: chronix
    image: 'hurence/historian-chronix:1.0.1-SNAPSHOT'
    networks:
      historian-be:
        aliases:
          - chronix

  frontend:
    container_name: historian-frontend
    image: 'hurence/historian-frontend:1.0.1-SNAPSHOT'
    ports:
      - 4200:80
    networks:
      historian-be:
        aliases:
          - frontend

  backend:
    container_name: historian-backend
    image: 'hurence/historian-backend:1.0.1-SNAPSHOT'
    environment:
      - sorl_base_url=${ENTRY_POINT_URL:-http://historian.hurence.com:10080}/solr
      - keycloak_base_url=${ENTRY_POINT_URL:-http://historian.hurence.com:10080}/auth
    networks:
      historian-be:
        aliases:
          - backend
  
  logisland:
    container_name: logisland
    image: 'hurence/historian-logisland:1.0.0-RC1-MIN'
    command: "bin/logisland.sh --conf /conf/historian-remote.yaml"
    ports:
      - '4050:4050'
    volumes:
      - ./conf/logisland:/conf
    networks:
      historian-be:
        aliases:
          - logisland

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - 'conf/grafana/env.grafana'
    networks:
      historian-be:
        aliases:
          - grafana
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ~/data/grafana:/var/lib/grafana
      - ./conf/grafana/provisioning/:/etc/grafana/provisioning/

  keycloak:
    container_name: keycloak
    image: 'hurence/historian-keycloak:1.0.1-SNAPSHOT'
    environment:
      - PROXY_ADDRESS_FORWARDING=true
    networks:
      historian-be:
        aliases:
          - keycloak
  
  nginx:
   container_name: nginx
   image: nginx:1.13
   restart: always
   ports:
     - 10080:10080
     - 10443:10443
   environment:
     - HISTORIAN_DOMAIN=${HISTORIAN_DOMAIN:-historian.hurence.com}
   volumes:
     - ./conf/nginx:/etc/nginx/conf.d
   networks:
     historian-be:
       aliases:
         - ${HISTORIAN_DOMAIN:-historian.hurence.com}
