version: "2"
services:

  chronix:
    container_name: chronix
    environment:
      - JAVA_MEMORY=4g
    hostname: chronix
    image: 'hurence/historian-chronix:0.4.4'
    ports:
      - '8983:8983'
    network_mode: bridge

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    network_mode: bridge

  keycloak:
    container_name: keycloak
    image: 'hurence/keycloak:0.2.0'
    ports:
      - '8080:8080'
    network_mode: bridge

