version: "2"
services:

  chronix:
    container_name: chronix
    environment:
      - JAVA_MEMORY=4g
    hostname: chronix
    image: 'hurence/historian-chronix:0.4.4'
    ports:
      - '8983:8983'
    network_mode: bridge

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    network_mode: bridge

  keycloak:
    container_name: keycloak
    image: 'hurence/keycloak:0.2.0'
    ports:
      - '8080:8080'
    network_mode: bridge

  historian-backend:
    container_name: historian-backend
    image: 'hurence/historian-backend:0.4.3'
    ports:
      - '8701:8701'
    links:
      - chronix
      - redis
      - keycloak
    network_mode: bridge

  historian-frontend:
    container_name: historian-frontend
    image: 'hurence/historian-frontend:0.4.3'
    ports:
      - '4200:80'
    links:
      - historian-backend
      - keycloak
    network_mode: bridge

  logisland:
    container_name: logisland
    image: 'hurence/logisland:0.14.1-develop'
    command: bin/logisland.sh --conf /conf/historian-remote.yaml
    hostname: logisland
    ports:
      - '4050:4050'
    volumes:
      - ./conf/logisland:/conf
    links:
      # - zookeeper
      # - kafka
      # - elasticsearch
      - chronix
      - redis
      - historian-backend
    network_mode: bridge
