version: "2"
services:

  chronix:
    container_name: chronix
    environment:
      - JAVA_MEMORY=4g
    hostname: chronix
    image: 'andrea/cronix:1.0'
    ports:
      - '8983:8983'
    network_mode: bridge

  keycloak:
    container_name: keycloak
    image: 'hurence/keycloak:0.2.0'
    ports:
      - '8080:8080'
    network_mode: bridge
  logisland:
      container_name: logisland
      image: 'hurence/logisland:GH-404'
      command: bin/logisland.sh --conf /conf/historian-remote.yaml
      hostname: logisland
      ports:
        - '4050:4050'
      volumes:
        - ./conf/logisland:/conf
      links:
        - chronix
      network_mode: bridge
      extra_hosts:
        - "historian-backend:192.168.99.1"
