server:
  port: ${appPort:8701}
  servlet-path: /

spring:
  application:
    name: logisland-historian
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-actuator-with-jersey
endpoints:
  enabled: true
  info:
    enabled: true
  health:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
  actuator:
    sensitive: false

# app name and build version updated during build process from Maven properties.
info:
  app:
    name: @project.artifactId@
  build:
    version: @project.version@

keycloak:
  auth-server-url: http://keycloak:8080/auth
  realm: logisland
  resource: logisland-historian
  public-client: true
  principal-attribute: preferred_username
  security-constraints:
    - authRoles:
        - user
      securityCollections:
        - patterns:
          - /api/v1/tags/*


redis:
  host: redis
  port: 6379

connections:
  opc-da:
    cls-id: F8582CF2-88FB-11D0-B850-00C0F0104305
    domain: OPC-9167C0D9342
    password: opc
    user: OPC
    refresh-period-millis: 100
    timeout-millis: 2000
    host: 192.168.56.101


solr:
  core: chronix
  host: chronix
  port: 8983





