server:
  port: ${appPort:8701}
  servlet:
    path: /


spring:
  application:
    name: logisland-historian
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  data:
    solr:
      host: http://chronix:8983/solr
  redis:
    host: redis
    port: 6379
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb




# app name and build version updated during build process from Maven properties.
info:
  app:
    name: @project.artifactId@
  build:
    version: @project.version@

keycloak:
  realm: logisland
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: logisland-historian
  public-client: true
  bearer-only: true
  use-resource-role-mappings: true
  confidential-port: 0
  principal-attribute: preferred_username
  cors: true
  cors-allowed-headers: "*"
  cors-allowed-methods: "*"
  cors-exposed-headers: "*"



management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
      cors:
        exposed-headers:
  endpoint:
    health:
      cache:
        time-to-live: 10s
      show-details: always
logisland:
  chronix:
    batch-size: 500
    default-collection: chronix
    connection-url: ${spring.data.solr.host}
    flush-interval: PT5S
    group-by-fields:
      - tag_id
      - quality
