server:
  port: 8701
  servlet:
    path: /
  address: 0.0.0.0


spring:
  application:
    name: logisland-historian
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  data:
    solr:
      host: ${sorl_base_url:http://historian.hurence.com:10080/solr}

  cache:
    type: simple
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb




# app name and build version updated during build process from Maven properties.
info:
  app:
    name: @project.artifactId@
  build:
    version: @project.version@

keycloak:
  realm: logisland
  auth-server-url: ${keycloak_base_url:http://historian.hurence.com:10080/auth}
  ssl-required: external
  resource: logisland-historian
  public-client: true
  bearer-only: true
  use-resource-role-mappings: true
  confidential-port: 0
  principal-attribute: preferred_username
  cors: true
  cors-allowed-headers: "*"
  cors-allowed-methods: "*"
  cors-exposed-headers: "*"
  proxy-url:



management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
      cors:
        exposed-headers:
  endpoint:
    health:
      cache:
        time-to-live: 10s
      show-details: always
logisland:
  opc-dataflow-name: OpcTagsInjector
  chronix:
    batch-size: 500
    default-collection: chronix
    connection-url: ${spring.data.solr.host}
    flush-interval: PT5S
    group-by-fields:
      - tag_id
      - quality
