server:
  port: ${appPort:8701}
  servlet:
    path: /


spring:
  application:
    name: logisland-historian
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  data:
    solr:
      host: http://chronix:8983/solr
  redis:
    host: redis
    port: 6379
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb




# app name and build version updated during build process from Maven properties.
info:
  app:
    name: @project.artifactId@
  build:
    version: @project.version@

keycloak:
  auth-server-url: http://keycloak:8080/auth
  realm: logisland
  resource: logisland-historian
  public-client: true
  principal-attribute: preferred_username
  security-constraints:
    - authRoles:
        - user
      securityCollections:
        - patterns:
          - /api/v1/tags/*
  cors: true
  cors-allowed-headers: "*"
  cors-allowed-methods: "*"
  cors-exposed-headers: "*"


connections:
  opc-da:
    cls-id: F8582CF2-88FB-11D0-B850-00C0F0104305
    domain: OPC-9167C0D9342
    password: opc
    user: OPC
    refresh-period-millis: 100
    timeout-millis: 2000
    host: 192.168.56.101

solr:
  core: chronix
  host: chronix
  port: 8983
management:

  endpoints:
    web:
      exposure:
        include: info, health, metrics






