swagger: '2.0'
info:
  version: v1
  title: Spring Boot + Jersey + Swagger + Docker Example
  contact:
    name: Thomas Bailet
basePath: /api
tags:
  - name: Hello resource
schemes:
  - http
  - https
paths:
  /hello:
    post:
      tags:
        - Hello resource
      summary: Creates hello resource. Version 1 - (version in Accept Header)
      description: ''
      operationId: createHelloVersionInAcceptHeader
      consumes:
        - application/vnd.asimio-v1+json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/Hello'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Hello'
        '201':
          description: hello resource created
          headers:
            Location:
              type: string
              description: The URL to retrieve created resource
  '/hello/{name}':
    get:
      tags:
        - Hello resource
      summary: Gets a hello resource. World Version 1 (version in Accept Header)
      description: ''
      operationId: getHelloVersionInAcceptHeader
      consumes:
        - application/vnd.asimio-v1+json
      produces:
        - application/vnd.asimio-v1+json
      parameters:
        - name: name
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Hello resource found
        '404':
          description: Hello resource not found
  /v1/hello:
    post:
      tags:
        - Hello resource
      summary: Creates hello resource. Version 1 - (version in URL)
      description: ''
      operationId: createHelloVersionInUrl
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/Hello'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Hello'
        '201':
          description: hello resource created
          headers:
            Location:
              type: string
              description: The URL to retrieve created resource
  '/v1/hello/{name}':
    get:
      tags:
        - Hello resource
      summary: Gets a hello resource. Version 1 - (version in URL)
      description: ''
      operationId: getHelloVersionInUrl
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Hello resource found
        '404':
          description: Hello resource not found
definitions:
  Hello:
    type: object
    properties:
      msg:
        type: string
