kapua-chronix:
  image: 'hurence/chronix:latest'
  net: host
  ports:
    - '8983:8983'
kapua-elasticsearch:
  command: /bin/bash bin/es-docker
  deployment_strategy: every_node
  environment:
    - ES_JAVA_OPTS=-Xms1g -Xmx1g
    - bootstrap.memory_lock=false
    - cluster.name=es-logisland
    - network.publish_host=0.0.0.0
    - xpack.security.enabled=false
    - xpack.watcher.enabled=false
    - cluster.name=kapua-datastore
    - discovery.type=single-node
    - transport.host=_site_
    - transport.ping_schedule=-1
    - transport.tcp.connect_timeout=30s
  image: 'docker.elastic.co/elasticsearch/elasticsearch:5.4.0'
  net: host
  ports:
    - '9200:9200'
    - '9300:9300'

kapua-sql:
  image: kapua/kapua-sql:0.3.1
  net: host
  ports:
    - '3306:3306'
    - '8181:8181'

kapua-broker:
  image: kapua/kapua-broker:0.3.1
  net: host
  environment: 
    - commons.db.schema.update=true
  ports:
    - '1883:1883'
    - '61614:61614'
  links: 
    - kapua-sql:db
    - kapua-elasticsearch:es

kapua-console:
  image: kapua/kapua-console:0.3.1
  net: host
  environment: 
    - commons.db.schema.update=true
  ports:
    - '8080:8080'
  links: 
    - kapua-sql:db  
    - kapua-broker:broker
    - kapua-elasticsearch:es

kapua-api:
  image: kapua/kapua-api:0.3.1
  net: host
  environment: 
    - commons.db.schema.update=true
  ports:
    - '8081:8080'
  links: 
    - kapua-sql:db  
    - kapua-broker:broker
    - kapua-elasticsearch:es
