server:
  port: ${appPort:8000}
  servlet-path: /


# Jersey dispatcher servlet
spring:
  application:
      name: springboot-jersey-swagger-docker
  jersey:
    application-path: /api

# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-actuator-with-jersey
endpoints:
  enabled: true
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

# app name and build version updated during build process from Maven properties.
info:
  app:
    name: @project.artifactId@
  build:
    version: @project.version@

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: logisland
  resource: logisland-historian
  public-client: true
  security-constraints:
    - authRoles:
        - user
      securityCollections:
        - patterns:
          - /products/*




