server:
  port: ${appPort:8000}
  servlet-path: /


# Jersey dispatcher servlet
spring:
  application:
      name: logisland-historian
  jersey:
    application-path: /api
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-actuator-with-jersey
endpoints:
  enabled: true
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

# app name and build version updated during build process from Maven properties.
info:
  app:
    name: @project.artifactId@
  build:
    version: @project.version@

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: logisland
  resource: logisland-historian
  public-client: true
  principal-attribute: preferred_username
  security-constraints:
    - authRoles:
        - user
      securityCollections:
        - patterns:
          - /tags/*


redis:
  host: localhost
  port: 6379

solr:
  core: chronix
  host: localhost
  port: 8983
